name: "Setup"
description: "Setup Composite Action"

inputs:
  path:
    description: "Path"
    default: "."

runs:
  using: "composite"

  steps:
    - name: Before Setup
      run: |
        pwd
        ls -al
        tree -a -I .git
        printenv
      shell: bash

    - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
      with:
        path: ${{ inputs.path }}/.fvmrc

    - name: After Setup
      run: |
        pwd
        ls -al
        tree -a -I .git
        printenv
      shell: bash

    - name: Version
      run: |
        flutter --version
        dart --version
      shell: bash
