name: "Check"
description: "Check Composite Action"

inputs:
  path:
    description: "Path"
    default: "."

runs:
  using: "composite"

  steps:
    - run: |
        cd ${{ inputs.path }}
        pwd
      shell: bash

    - name: Analyze
      run: |
        pwd
        flutter analyze
      shell: bash

    - name: Test
      run: |
        dart pub global activate junitreport
        flutter test --machine | tojunit --output test-report.xml
      shell: bash

    - uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: test-report.xml
        annotate_only: true
        detailed_summary: true
